#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from sintatica.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "sintatica.y"

#include <iostream>
#include <string>
#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <stack>
#include <queue> 
#include <ctype.h>
#include <regex>

#define YYSTYPE atributos

using namespace std;

struct variavel
{
	string nome;
	string tipo;
	string identificacao;
};

struct atributos
{
	string label;
	string traducao;
	string tipo;
};

struct laco
{
	string labelinicio;
	string labelfim;
};

struct _switch
{
	string var;
	string comp;
	string res;
	string tipo;
	bool hasDefault;
	int defaultQtt;
};

struct _function
{
	vector <variavel> functionContext;
	stack <_function> fctx;
	string label;
};

vector < vector < variavel> > pilhaContextoVariavel;
vector < laco > pilhaLaco;
stack <_function> functions;
stack <string> labelStackEnd;

stack <_switch> switchVar;

string declaracoes;

int tempGenQtt = 0;
int nomeGenQtt = 0;
int lacoQtt = 0;
int caseQtt = 0;

//Verifica se já existe uma variável com esse nome
bool existeNome(string nome);

//Empilha um contexto
void empilhaContexto()
{
	vector <variavel> tabelaVariaveis;

	pilhaContextoVariavel.push_back(tabelaVariaveis);

}

string gerarLabelEndif(void)
{
	char buffer[64];
	static unsigned i;

	sprintf(buffer,"endif%i", i++);

	return buffer;
}

string gerarLabel(int base)
{
	char buffer[64];
	static unsigned i;

	sprintf(buffer,"L%i", base+i++);

	return buffer;
}


void desempilhaContexto()
{
	//Guarda as variáveis declaradas
	vector <variavel> tabelaVariaveis = pilhaContextoVariavel.back();

	//Percorre dentro de um contexto do mais recente ao mais antigo
	for(std::vector<variavel>::reverse_iterator it = tabelaVariaveis.rbegin(); it != tabelaVariaveis.rend(); it++)    
	{

		//Aponta pra uma variável
		variavel temp = *it;

		declaracoes = "\t" + temp.tipo + " " + temp.identificacao + ";\n" + declaracoes ;
    
	}

	pilhaContextoVariavel.pop_back();
}

string genTemp()
{
	return "temp" + to_string(tempGenQtt++);
}
string genNomeGen()
{
	return to_string(nomeGenQtt++);
}

//Insere símbolo na tabela de variáveis
void insereVariavel(string nome, string tipo, string identificacao)
{

	//Se o nome existe na tabela
	if (existeNome(nome))
	{
		cout << "\tErro: Redeclaração do " + nome + "\n";	
		exit(1);	
	}

	variavel novaVariavel;
	novaVariavel.nome = nome;
	novaVariavel.tipo = tipo;
	novaVariavel.identificacao = identificacao;


	
	//Adiciona variável no último contexto
	pilhaContextoVariavel.back().push_back(novaVariavel);


}

//Verifica se existe um nome na tabela de variáveis
bool existeNome(string nome)
{

	vector <variavel> tabelaVariaveis = pilhaContextoVariavel.back();

	if (tabelaVariaveis.size() == 0)
			return false;
	

	for(std::vector<variavel>::iterator it = tabelaVariaveis.begin(); it != tabelaVariaveis.end(); it++)    
	{

		variavel temp = *it;

		if (!temp.nome.compare(nome))
			return true;
    
	}

	return false;
}

//Busca por uma variável declarada
void buscaVariavel(string nome, variavel &var)
{

	//Percorre os contextos do fim ao início
	for(std::vector< vector <variavel> >::reverse_iterator it = pilhaContextoVariavel.rbegin(); it != pilhaContextoVariavel.rend(); it++)    
	{

		//Aponta para um contexto
		vector <variavel> tabelaVariaveis = *it;

		//Se não tem variável declarada
		if (tabelaVariaveis.size() == 0)
			continue;
	
		//Percorre dentro de um contexto
		for(std::vector<variavel>::iterator it = tabelaVariaveis.begin(); it != tabelaVariaveis.end(); it++)    
		{

			//Aponta pra uma variável
			variavel temp = *it;

			//Se achou o nome
			if (!temp.nome.compare(nome))
			{
				var = temp;
				return;
			}
    
		}

	}

	//Sinaliza erro
	cout << "\tErro: " + nome + " não declarado\n";
	exit(1);	
	
}


//Atualiza os valores de uma expressão aritmética
void atualizaRegraExprAritimetica(atributos &E1, atributos &E2)
{
	//INT x FLOAT -> (float)
	if (!E1.tipo.compare("int")
	&& !E2.tipo.compare("real"))
	{
		//Criação de variável temporária
		string nomeTemp = genTemp();

		//Tenta inserir variável
		insereVariavel(genNomeGen(), "real", nomeTemp);

		E1.tipo = "real";
		E1.traducao = E1.traducao + "\t" + nomeTemp + " = (Real) " + E1.label + ";\n"; 
		E1.label = nomeTemp;
	}
	else if (!E1.tipo.compare("real")
	&& !E2.tipo.compare("int"))
	{
		//Criação de variável temporária
		string nomeTemp = genTemp();

		//Tenta inserir variável
		insereVariavel(genNomeGen(), "real", nomeTemp);

		E2.tipo = "real";
		E2.traducao = E2.traducao + "\t" + nomeTemp + " = (Real) " + E2.label + ";\n"; 
		E2.label = nomeTemp;
	}
	//Se os tipos são diferentes e desconhecidos
	else if (E1.tipo.compare(E2.tipo))
	{
		cout << "\tErro: Não é possível conversão entre " + E1.tipo + " e " + E2.tipo + ";\n";
		exit(1);
	}
}

//Verifica se pode uma atribuição
void verificaAtribuicao (string tipo1, string tipo2)
{
	if (!tipo1.compare("null") || !tipo2.compare("null"))
		return;

	if (!tipo1.compare("int"))
	{
		if(!tipo2.compare("int")
			||!tipo2.compare("BOOL"))
			return;
	}
	else if (!tipo1.compare("real"))
	{
		if(!tipo2.compare("int")
			|| !tipo2.compare("real"))
			return;
		
	}
	else if (!tipo1.compare("char"))
	{
		if(!tipo2.compare("char"))
			return;
	}
	else if (!tipo1.compare("BOOL"))
	{
		if(!tipo2.compare("BOOL")
			|| !tipo2.compare("int"))
			return;		
	}
	else if (!tipo1.compare("char*"))
	{
		if(!tipo2.compare("char*"))
			return;		
	}


	cout << "\tErro: não pôde converter de " + tipo2 + " para " + tipo1 + "\n";
	exit(1);
}

int yylex(void);
void yyerror(string);
string genTemp();
string genNomeGen();

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	TK_IS	258
#define	TK_NUM	259
#define	TK_REAL	260
#define	TK_BOOL	261
#define	TK_CHAR	262
#define	TK_WHILE	263
#define	TK_FOR	264
#define	TK_DO	265
#define	TK_BREAK	266
#define	TK_CONTINUE	267
#define	TK_MAIN	268
#define	TK_ID	269
#define	TK_TIPO_INT	270
#define	TK_TIPO_REAL	271
#define	TK_TIPO_BOOL	272
#define	TK_TIPO_CHAR	273
#define	TK_STRING	274
#define	TK_TIPO_STRING	275
#define	TK_FIM	276
#define	TK_ERROR	277
#define	TK_INPUT	278
#define	TK_OUTPUT	279
#define	TK_SWITCH	280
#define	TK_CASE	281
#define	TK_DEFAULT	282
#define	TK_IF	283
#define	TK_ELSE	284
#define	TK_FUNCTION	285
#define	TK_RETURN	286
#define	TK_PROCEDURE	287


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int TK_IS;
static const int TK_NUM;
static const int TK_REAL;
static const int TK_BOOL;
static const int TK_CHAR;
static const int TK_WHILE;
static const int TK_FOR;
static const int TK_DO;
static const int TK_BREAK;
static const int TK_CONTINUE;
static const int TK_MAIN;
static const int TK_ID;
static const int TK_TIPO_INT;
static const int TK_TIPO_REAL;
static const int TK_TIPO_BOOL;
static const int TK_TIPO_CHAR;
static const int TK_STRING;
static const int TK_TIPO_STRING;
static const int TK_FIM;
static const int TK_ERROR;
static const int TK_INPUT;
static const int TK_OUTPUT;
static const int TK_SWITCH;
static const int TK_CASE;
static const int TK_DEFAULT;
static const int TK_IF;
static const int TK_ELSE;
static const int TK_FUNCTION;
static const int TK_RETURN;
static const int TK_PROCEDURE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,TK_IS=258
	,TK_NUM=259
	,TK_REAL=260
	,TK_BOOL=261
	,TK_CHAR=262
	,TK_WHILE=263
	,TK_FOR=264
	,TK_DO=265
	,TK_BREAK=266
	,TK_CONTINUE=267
	,TK_MAIN=268
	,TK_ID=269
	,TK_TIPO_INT=270
	,TK_TIPO_REAL=271
	,TK_TIPO_BOOL=272
	,TK_TIPO_CHAR=273
	,TK_STRING=274
	,TK_TIPO_STRING=275
	,TK_FIM=276
	,TK_ERROR=277
	,TK_INPUT=278
	,TK_OUTPUT=279
	,TK_SWITCH=280
	,TK_CASE=281
	,TK_DEFAULT=282
	,TK_IF=283
	,TK_ELSE=284
	,TK_FUNCTION=285
	,TK_RETURN=286
	,TK_PROCEDURE=287


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::TK_IS=258;
const int YY_parse_CLASS::TK_NUM=259;
const int YY_parse_CLASS::TK_REAL=260;
const int YY_parse_CLASS::TK_BOOL=261;
const int YY_parse_CLASS::TK_CHAR=262;
const int YY_parse_CLASS::TK_WHILE=263;
const int YY_parse_CLASS::TK_FOR=264;
const int YY_parse_CLASS::TK_DO=265;
const int YY_parse_CLASS::TK_BREAK=266;
const int YY_parse_CLASS::TK_CONTINUE=267;
const int YY_parse_CLASS::TK_MAIN=268;
const int YY_parse_CLASS::TK_ID=269;
const int YY_parse_CLASS::TK_TIPO_INT=270;
const int YY_parse_CLASS::TK_TIPO_REAL=271;
const int YY_parse_CLASS::TK_TIPO_BOOL=272;
const int YY_parse_CLASS::TK_TIPO_CHAR=273;
const int YY_parse_CLASS::TK_STRING=274;
const int YY_parse_CLASS::TK_TIPO_STRING=275;
const int YY_parse_CLASS::TK_FIM=276;
const int YY_parse_CLASS::TK_ERROR=277;
const int YY_parse_CLASS::TK_INPUT=278;
const int YY_parse_CLASS::TK_OUTPUT=279;
const int YY_parse_CLASS::TK_SWITCH=280;
const int YY_parse_CLASS::TK_CASE=281;
const int YY_parse_CLASS::TK_DEFAULT=282;
const int YY_parse_CLASS::TK_IF=283;
const int YY_parse_CLASS::TK_ELSE=284;
const int YY_parse_CLASS::TK_FUNCTION=285;
const int YY_parse_CLASS::TK_RETURN=286;
const int YY_parse_CLASS::TK_PROCEDURE=287;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		191
#define	YYFLAG		-32768
#define	YYNTBASE	48

#define YYTRANSLATE(x) ((unsigned)(x) <= 287 ? yytranslate[x] : 88)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    43,     2,     2,     2,     2,     2,     2,    37,
    38,    35,    33,    47,    34,     2,    36,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    46,    40,    44,
    39,    45,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    41,     2,    42,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     3,     4,    11,    25,    34,    37,    40,    46,
    52,    53,    54,    57,    59,    60,    63,    65,    66,    69,
    72,    75,    78,    81,    82,    84,    88,    93,    95,    97,
    99,   101,   103,   105,   107,   109,   111,   113,   119,   125,
   127,   129,   131,   133,   135,   137,   139,   143,   145,   147,
   149,   151,   153,   156,   159,   162,   165,   167,   169,   173,
   177,   181,   185,   187,   189,   191,   196,   198,   205,   214,
   216,   218,   220,   223,   225,   226,   231,   235,   243,   246,
   247,   258,   259,   263,   265,   267,   268,   272,   273,   275,
   278,   287,   291,   292
};

static const short yyrhs[] = {    57,
     0,     0,     0,     8,    37,    68,    38,    49,    54,     0,
     9,    37,    71,    39,    71,    40,    68,    40,    71,    59,
    38,    49,    54,     0,    10,    49,    54,     8,    37,    68,
    38,    40,     0,    11,    40,     0,    12,    40,     0,    15,
    13,    37,    38,    54,     0,    56,    41,    58,    42,    55,
     0,     0,     0,    63,    57,     0,    53,     0,     0,    63,
    58,     0,    54,     0,     0,    39,     7,     0,    39,     6,
     0,    39,    71,     0,    39,    68,     0,    39,    60,     0,
     0,    19,     0,    72,    59,    40,     0,    67,    72,    59,
    40,     0,    62,     0,    61,     0,    73,     0,    51,     0,
    52,     0,    64,     0,    65,     0,    79,     0,    85,     0,
    80,     0,    23,    37,    72,    38,    40,     0,    24,    37,
    66,    38,    40,     0,    19,     0,    72,     0,    15,     0,
    16,     0,    17,     0,    18,     0,    20,     0,    69,    70,
    69,     0,    69,     0,    71,     0,     7,     0,     6,     0,
    68,     0,    39,    39,     0,    43,    39,     0,    44,    39,
     0,    45,    39,     0,    45,     0,    44,     0,    71,    36,
    71,     0,    71,    35,    71,     0,    71,    33,    71,     0,
    71,    34,    71,     0,     4,     0,     5,     0,    14,     0,
    37,    67,    38,    14,     0,    14,     0,    28,    37,    68,
    38,    54,    78,     0,    25,    37,    72,    38,    50,    41,
    75,    42,     0,     4,     0,     7,     0,    19,     0,    76,
    75,     0,    77,     0,     0,    26,    74,    46,    58,     0,
    27,    46,    58,     0,    29,    28,    37,    68,    38,    54,
    78,     0,    29,    54,     0,     0,    30,    72,    37,    84,
    82,    38,    31,    67,     3,    54,     0,     0,    31,    81,
    40,     0,    71,     0,    19,     0,     0,    83,    84,    82,
     0,     0,    47,     0,    67,    72,     0,    72,    39,    72,
    37,    87,    86,    38,    40,     0,    47,    87,    86,     0,
     0,    72,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
   317,   357,   374,   390,   413,   431,   444,   460,   496,   502,
   509,   516,   523,   527,   531,   537,   542,   546,   554,   560,
   571,   579,   586,   592,   600,   623,   646,   671,   676,   681,
   685,   689,   693,   697,   701,   705,   709,   715,   727,   733,
   755,   767,   772,   776,   780,   784,   792,   877,   896,   914,
   919,   929,   937,   941,   945,   949,   953,   957,   963,   986,
  1010,  1034,  1058,  1064,  1072,  1086,  1108,  1115,  1127,  1149,
  1155,  1160,  1166,  1170,  1174,  1180,  1211,  1216,  1234,  1245,
  1252,  1263,  1265,  1270,  1274,  1278,  1283,  1287,  1292,  1297,
  1315,  1320,  1324,  1329
};

static const char * const yytname[] = {   "$","error","$illegal.","TK_IS","TK_NUM",
"TK_REAL","TK_BOOL","TK_CHAR","TK_WHILE","TK_FOR","TK_DO","TK_BREAK","TK_CONTINUE",
"TK_MAIN","TK_ID","TK_TIPO_INT","TK_TIPO_REAL","TK_TIPO_BOOL","TK_TIPO_CHAR",
"TK_STRING","TK_TIPO_STRING","TK_FIM","TK_ERROR","TK_INPUT","TK_OUTPUT","TK_SWITCH",
"TK_CASE","TK_DEFAULT","TK_IF","TK_ELSE","TK_FUNCTION","TK_RETURN","TK_PROCEDURE",
"'+'","'-'","'*'","'/'","'('","')'","'='","';'","'{'","'}'","'!'","'<'","'>'",
"':'","','","S","EMPLACO","EMPSWITCH","LACO","INTLACO","MAIN","BLOCO","DESCONTEXTO",
"EMPCONTEXTO","CMDSGLOBAL","COMANDOS","OPATRIB","ES","ATRIBUICAO","DECLARACAO",
"COMANDO","INPUT","OUTPUT","OUTTERM","TIPO","EL","OPNDOLOGIC","OPLOGIC","E",
"ID","CONDICIONAL","CASE_COMP","CASES","CASE","DEFAULT","CONDMODIF","FUNCTION",
"RETURN","IT","ARGS","VIRG","PAR","CALL_FUNC","MORE_PARS","ONE_PAR",""
};
#endif

static const short yyr1[] = {     0,
    48,    49,    50,    51,    51,    51,    52,    52,    53,    54,
    55,    56,    57,    57,    57,    58,    58,    58,    59,    59,
    59,    59,    59,    59,    60,    61,    62,    63,    63,    63,
    63,    63,    63,    63,    63,    63,    63,    64,    65,    66,
    66,    67,    67,    67,    67,    67,    68,    68,    69,    69,
    69,    69,    70,    70,    70,    70,    70,    70,    71,    71,
    71,    71,    71,    71,    71,    71,    72,    73,    73,    74,
    74,    74,    75,    75,    75,    76,    77,    78,    78,    78,
    79,    79,    80,    81,    81,    81,    82,    82,    83,    84,
    85,    86,    86,    87
};

static const short yyr2[] = {     0,
     1,     0,     0,     6,    13,     8,     2,     2,     5,     5,
     0,     0,     2,     1,     0,     2,     1,     0,     2,     2,
     2,     2,     2,     0,     1,     3,     4,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     5,     5,     1,
     1,     1,     1,     1,     1,     1,     3,     1,     1,     1,
     1,     1,     2,     2,     2,     2,     1,     1,     3,     3,
     3,     3,     1,     1,     1,     4,     1,     6,     8,     1,
     1,     1,     2,     1,     0,     4,     3,     7,     2,     0,
    10,     0,     3,     1,     1,     0,     3,     0,     1,     2,
     8,     3,     0,     1
};

static const short yydefact[] = {    15,
     0,     0,     2,     0,     0,    67,    42,    43,    44,    45,
    46,     0,     0,     0,     0,     0,    86,    31,    32,    14,
     1,    29,    28,    15,    33,    34,     0,    24,    30,    35,
    37,    36,     0,     0,    12,     7,     8,     0,     0,     0,
     0,     0,     0,    63,    64,    65,    85,     0,    84,     0,
    13,    24,     0,     0,    51,    50,    52,    48,    49,     0,
     0,     0,     0,     0,    40,     0,    41,     0,    52,     0,
    42,     0,     0,     0,     0,     0,    83,     0,     0,    51,
    50,    65,    25,    23,    52,    49,     0,    26,     2,     0,
     0,    58,    57,     0,     0,     0,    12,    12,     0,     0,
     3,    12,     0,    88,     0,    61,    62,    60,    59,    27,
     0,    12,    53,    54,    55,    56,    52,    47,     0,     0,
    17,     0,    18,     9,    38,    39,     0,    80,    90,    89,
     0,     0,    66,    94,    93,     4,     0,    52,    11,    16,
    75,    12,    68,     0,    88,     0,     0,    52,     0,    10,
     0,     0,     0,    75,    74,     0,    79,     0,    87,    93,
     0,     0,     6,    70,    71,    72,     0,    12,    69,    73,
     0,     0,    92,    91,    24,    18,    77,    52,    12,     0,
    76,    12,    81,     2,    80,    12,    78,     5,     0,     0,
     0
};

static const short yydefgoto[] = {   189,
    35,   127,    18,    19,    20,   121,   150,    62,    21,   122,
    54,    84,    22,    23,   123,    25,    26,    66,    27,    85,
    58,    94,    59,    28,    29,   167,   153,   154,   155,   143,
    30,    31,    50,   131,   132,   104,    32,   147,   135
};

static const short yypact[] = {   201,
   -25,   -20,-32768,    -9,     5,-32768,    11,-32768,-32768,-32768,
-32768,    13,    24,    29,    47,    71,    68,-32768,-32768,-32768,
-32768,-32768,-32768,   201,-32768,-32768,    71,    49,-32768,-32768,
-32768,-32768,    37,     2,-32768,-32768,-32768,    52,    71,    -4,
    71,    37,    65,-32768,-32768,-32768,-32768,   120,   143,    46,
-32768,    58,    15,    63,-32768,-32768,    66,    10,   143,    60,
    98,    72,    77,    79,-32768,    85,-32768,    89,    94,   120,
-32768,   101,     2,     2,     2,     2,-32768,    64,    84,   -15,
    -2,   104,-32768,-32768,     8,    76,   106,-32768,-32768,   109,
   110,   111,   118,    37,     2,   108,   144,-32768,   123,   125,
-32768,-32768,    71,   119,   156,    40,    40,-32768,-32768,-32768,
    71,-32768,-32768,-32768,-32768,-32768,-32768,    10,    86,    37,
-32768,   129,   173,-32768,-32768,-32768,   132,   151,-32768,-32768,
   154,   120,-32768,-32768,   147,-32768,    37,   157,-32768,-32768,
    54,   171,-32768,   169,   119,    71,   164,   165,   166,-32768,
    28,   161,   178,    54,-32768,   185,-32768,   120,-32768,   147,
   168,     2,-32768,-32768,-32768,-32768,   177,   144,-32768,-32768,
    37,   224,-32768,-32768,    95,   173,-32768,   190,-32768,   192,
-32768,-32768,-32768,-32768,   151,-32768,-32768,-32768,   233,   234,
-32768
};

static const short yypgoto[] = {-32768,
   -84,-32768,-32768,-32768,-32768,   -35,-32768,-32768,   211,  -112,
   -50,-32768,-32768,-32768,     9,-32768,-32768,-32768,   -40,   -29,
   142,-32768,   -16,   -13,-32768,-32768,    83,-32768,-32768,    53,
-32768,-32768,-32768,    96,-32768,   107,-32768,    80,    97
};


#define	YYLAST		243


static const short yytable[] = {    61,
    49,    79,    43,    57,   112,    44,    45,    72,    24,     6,
   140,    33,    69,    52,    65,    46,    34,    60,    44,    45,
    80,    81,   -20,    38,   -20,    64,    67,    68,    82,   103,
    36,   164,    24,    83,   165,   -19,    86,   -19,    48,    87,
    44,    45,    55,    56,    37,   -22,   166,   -22,    90,    39,
    46,    48,    91,    92,    93,   177,   106,   107,   108,   109,
    40,    86,   124,   181,   117,    41,   128,    44,    45,    80,
    81,    44,    45,    48,    75,    76,   136,    46,   119,   151,
   152,    46,    83,    42,     6,    77,    47,    53,    63,   129,
   138,   103,    73,    74,    75,    76,    78,   134,    95,   186,
    48,    70,    88,    89,    48,    96,   157,   148,    73,    74,
    75,    76,    97,   -21,    98,   -21,    99,   172,    73,    74,
    75,    76,   100,   110,   180,   137,   101,    73,    74,    75,
    76,   102,   134,    78,    71,     8,     9,    10,   105,    11,
   -67,   178,   111,   183,   120,   175,   185,   113,   114,   115,
   188,     1,     2,     3,     4,     5,   116,     6,    71,     8,
     9,    10,   125,    11,   126,   130,    12,    13,    14,   133,
   139,    15,   141,    16,    17,    73,    74,    75,    76,   142,
     1,     2,     3,     4,     5,   -18,     6,    71,     8,     9,
    10,   144,    11,   146,   149,    12,    13,    14,   156,   158,
    15,   161,    16,    17,   162,   163,   168,   174,     1,     2,
     3,     4,     5,   -12,     6,     7,     8,     9,    10,   169,
    11,   171,   176,    12,    13,    14,   179,   182,    15,   184,
    16,    17,   190,   191,    51,   118,   170,   187,   145,   173,
   159,     0,   160
};

static const short yycheck[] = {    35,
    17,    52,    16,    33,    89,     4,     5,    48,     0,    14,
   123,    37,    42,    27,    19,    14,    37,    34,     4,     5,
     6,     7,    38,    13,    40,    39,    40,    41,    14,    70,
    40,     4,    24,    19,     7,    38,    53,    40,    37,    53,
     4,     5,     6,     7,    40,    38,    19,    40,    39,    37,
    14,    37,    43,    44,    45,   168,    73,    74,    75,    76,
    37,    78,    98,   176,    94,    37,   102,     4,     5,     6,
     7,     4,     5,    37,    35,    36,   112,    14,    95,    26,
    27,    14,    19,    37,    14,    40,    19,    39,    37,   103,
   120,   132,    33,    34,    35,    36,    39,   111,    39,   184,
    37,    37,    40,    38,    37,     8,   142,   137,    33,    34,
    35,    36,    41,    38,    38,    40,    38,   158,    33,    34,
    35,    36,    38,    40,   175,    40,    38,    33,    34,    35,
    36,    38,   146,    39,    15,    16,    17,    18,    38,    20,
    37,   171,    37,   179,    37,   162,   182,    39,    39,    39,
   186,     8,     9,    10,    11,    12,    39,    14,    15,    16,
    17,    18,    40,    20,    40,    47,    23,    24,    25,    14,
    42,    28,    41,    30,    31,    33,    34,    35,    36,    29,
     8,     9,    10,    11,    12,    42,    14,    15,    16,    17,
    18,    38,    20,    47,    38,    23,    24,    25,    28,    31,
    28,    38,    30,    31,    40,    40,    46,    40,     8,     9,
    10,    11,    12,    41,    14,    15,    16,    17,    18,    42,
    20,    37,    46,    23,    24,    25,     3,    38,    28,    38,
    30,    31,     0,     0,    24,    94,   154,   185,   132,   160,
   145,    -1,   146
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 318 "sintatica.y"
{
				desempilhaContexto();

				cout << "#define TRUE 1\n#define FALSE 0\n#define BOOL int\n\n" 
				+ declaracoes + "\n" +  yyvsp[0].traducao + "\n";

				//Regex para dar free em char*
				//Toda variável temp_s tem um char* com mesmo numero de temp
				regex rgx("int temp\\d*\\_s");

				string prefixo = "int ";
				string posfixo = "_s";
				
				//Percorre o Regex e acha uma temporária temp_s
				for(sregex_iterator it(declaracoes.begin(), declaracoes.end(), rgx), it_end; it != it_end; ++it )
        		{
        			//Recebe a temporária
        			string temp = (*it)[0];
					
					//Remove o prefixo
					std::string::size_type i = temp.find(prefixo);
					if (i != std::string::npos)
   						temp.erase(i, prefixo.length());

   					//Remove o posfixo
   					i = temp.find(posfixo);
					if (i != std::string::npos)
   						temp.erase(i, posfixo.length());

   					cout << "\tfree(" + temp + ");\n";
        		}	

        		cout << "}\n";

        		//cout << (*it)[0] << "\n";
			;
    break;}
case 2:
#line 358 "sintatica.y"
{

				string inicioLabel = "inicioLaco" + to_string(lacoQtt);
				string fimLabel = "fimLaco" + to_string(lacoQtt);

				//Insere na pilha
				laco novoLaco;
				novoLaco.labelinicio = inicioLabel;
				novoLaco.labelfim = fimLabel;
				pilhaLaco.push_back(novoLaco);

				lacoQtt++;

			;
    break;}
case 3:
#line 375 "sintatica.y"
{

				string inicioLabel = "inicioSwitch" + to_string(lacoQtt);
				string fimLabel = "fimSwitch" + to_string(lacoQtt);

				//Insere na pilha
				laco newSwitch;
				newSwitch.labelinicio = inicioLabel;
				newSwitch.labelfim = fimLabel;
				pilhaLaco.push_back(newSwitch);

				lacoQtt++;
			;
    break;}
case 4:
#line 391 "sintatica.y"
{
				//Pega as labels na pilha do Laço atual
				laco lacoAtual = pilhaLaco.back();

				//Criação de variável temporária
				string nometemp = genTemp();

				//Adiciona na tabela
				insereVariavel(genNomeGen(), "BOOL", nometemp);
				
				yyval.traducao = "\n\t" + lacoAtual.labelinicio + ":\n" + 
					yyvsp[-3].traducao +
					"\t" + nometemp + " = !" + yyvsp[-3].label + ";\n" +
					"\tif(" + nometemp + ")\n\t" + "goto " + lacoAtual.labelfim + ";\n" +
					yyvsp[0].traducao +
					"\tgoto " + lacoAtual.labelinicio + ";\n" + 
					"\t" + lacoAtual.labelfim + ":\n\n";

				//Desempilha laço
				pilhaLaco.pop_back();

			;
    break;}
case 5:
#line 414 "sintatica.y"
{

				//Pega as labels na pilha do Laço atual
				laco lacoAtual = pilhaLaco.back();

				//Criação de variável temporária
				string nometemp = genTemp();

				//Adiciona na tabela
				insereVariavel(genNomeGen(), "BOOL", nometemp);		

				yyval.traducao =   "\t" + yyvsp[-10].label + " = " + yyvsp[-8].label + "\n\t" + lacoAtual.labelinicio +  "\n" +  yyvsp[-6].traducao + "\t" + nometemp + " != " + yyvsp[-6].label + "\n" + "\tif(" + nometemp + 
				") goto" + lacoAtual.labelfim + "\n" + yyvsp[0].traducao  + yyvsp[-3].traducao  + "\t" + yyvsp[-10].label + " = " + yyvsp[-3].label + "\n\tgoto" +  lacoAtual.labelinicio +  "\n" + "\t" + lacoAtual.labelfim + ":" "\n";

				//Desempilha laço
				pilhaLaco.pop_back();
			;
    break;}
case 6:
#line 431 "sintatica.y"
{

				//Pega as labels na pilha do Laço atual
				laco lacoAtual = pilhaLaco.back();

				yyval.traducao = "\t" + lacoAtual.labelinicio + "\n"+ yyvsp[-5].traducao + "\tif(" + yyvsp[-2].label + ") goto " + lacoAtual.labelinicio + "\n\t" + lacoAtual.labelfim + "\n";

				//Desempilha laço
				pilhaLaco.pop_back();

			;
    break;}
case 7:
#line 445 "sintatica.y"
{
				//Verifica se há um contexto de laço em questão
				if (pilhaLaco.size() == 0)
				{
					cout << "\tbreak fora de um laço!\n";
					exit(3);
				}

				//Pega as labels na pilha do Laço atual
				laco lacoAtual = pilhaLaco.back();

				//Realiza o desvio do laço em questão
				yyval.traducao = "\tgoto " + lacoAtual.labelfim + ";\n";

			;
    break;}
case 8:
#line 461 "sintatica.y"
{
				//Verifica se há um contexto de laço em questão
				if (pilhaLaco.size() == 0)
				{
					cout << "\tcontinue fora de um laço!\n";
					exit(3);
				}

				laco lacoAtual;

				//Enquanto o contexto atual for de case percorre todos os contextos em busca de um laço
				for(std::vector< laco >::reverse_iterator it = pilhaLaco.rbegin(); it != pilhaLaco.rend(); it++)
				{
					//Pega as labels na pilha do Laço atual
					lacoAtual = *it;

					if (!(lacoAtual.labelinicio.find("case") != std::string::npos))
						break;
				}

				//Se ele parou em um contexto de case então acusa erro
				if (lacoAtual.labelinicio.find("case") != std::string::npos)
				{

					cout << "\tcontinue fora de um laço!\n";
					exit(3);
				}


				//Realiza o desvio do laço em questão
				yyval.traducao = "\tgo to " + lacoAtual.labelinicio + ";\n";

			;
    break;}
case 9:
#line 497 "sintatica.y"
{
				yyval.traducao = "\nint main (void)\n{\n" + yyvsp[0].traducao;
			;
    break;}
case 10:
#line 503 "sintatica.y"
{
				yyval.traducao = yyvsp[-2].traducao;

			;
    break;}
case 11:
#line 510 "sintatica.y"
{

				desempilhaContexto();
			;
    break;}
case 12:
#line 517 "sintatica.y"
{

				
				empilhaContexto();
			;
    break;}
case 13:
#line 524 "sintatica.y"
{
				yyval.traducao = yyvsp[-1].traducao + yyvsp[0].traducao;
			;
    break;}
case 14:
#line 528 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 15:
#line 532 "sintatica.y"
{
				yyval.traducao = "";
			;
    break;}
case 16:
#line 538 "sintatica.y"
{
				yyval.traducao = yyvsp[-1].traducao + yyvsp[0].traducao;
				
			;
    break;}
case 17:
#line 543 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 18:
#line 547 "sintatica.y"
{
				yyval.traducao = "";
			;
    break;}
case 19:
#line 555 "sintatica.y"
{

				yyval.label = yyvsp[0].label;
				yyval.tipo = "char";
			;
    break;}
case 20:
#line 561 "sintatica.y"
{

				//$$.label = $2.label;
			if (yyvsp[0].label.compare("true"))
				yyval.label = "FALSE";
			else
				yyval.label = "TRUE";

				yyval.tipo = "BOOL";
			;
    break;}
case 21:
#line 572 "sintatica.y"
{
				
				yyval.label = yyvsp[0].label;
				yyval.traducao = yyvsp[0].traducao;
				yyval.tipo = yyvsp[0].tipo;
			;
    break;}
case 22:
#line 580 "sintatica.y"
{
				
				yyval.label = yyvsp[0].label;
				yyval.traducao = yyvsp[0].traducao;
				yyval.tipo = yyvsp[0].tipo;
			;
    break;}
case 23:
#line 587 "sintatica.y"
{
				yyval.label = yyvsp[0].label;
				yyval.traducao = yyvsp[0].traducao;
				yyval.tipo = yyvsp[0].tipo;
			;
    break;}
case 24:
#line 593 "sintatica.y"
{
			
				yyval.tipo = "null";
			;
    break;}
case 25:
#line 601 "sintatica.y"
{

				//Cria e insere variáveis
				string nomeTemp1 = genTemp();
				insereVariavel(genNomeGen(), "char*" , nomeTemp1);

				string nomeTemp2 = nomeTemp1 + "_s";
				insereVariavel(genNomeGen(), "int" , nomeTemp2);

				int size = yyvsp[0].label.length() - 1;

				yyval.traducao = "\t" + nomeTemp2 + " = " + to_string(size) + ";\n"
				+ "\t" + nomeTemp1 + " = (char*) malloc (sizeof(char) * " + nomeTemp2 + ");\n"
				+ "\t" + "strcpy(" + nomeTemp1 + ", " + yyvsp[0].label + ");\n";

				yyval.tipo = "char*";

				yyval.label = nomeTemp1;
			;
    break;}
case 26:
#line 624 "sintatica.y"
{
				
				//Variavel ID
				variavel var;
				
				buscaVariavel(yyvsp[-2].label, var);
				
				//Compara atribuição 
				verificaAtribuicao(var.tipo, yyvsp[-1].tipo);
				
				//Verifica se teve atribuição
				if (yyvsp[-1].tipo.compare("null"))
				{
					if (var.tipo.compare(yyvsp[-1].tipo))
						yyval.traducao = yyvsp[-1].traducao + "\t" + var.identificacao + " = (" + var.tipo + ") " + yyvsp[-1].label + ";\n";
					else
						yyval.traducao = yyvsp[-1].traducao + "\t" + var.identificacao + " = " + yyvsp[-1].label + ";\n";
				}
			;
    break;}
case 27:
#line 647 "sintatica.y"
{

				//Criação de variável temporária
				string nomeTemp = genTemp();
				
				
				//Tenta inserir variável
				insereVariavel(yyvsp[-2].label, yyvsp[-3].tipo , nomeTemp);

				//Verifica se a atribuição pode ocorrer de acordo com os tipos
				verificaAtribuicao(yyvsp[-3].tipo, yyvsp[-1].tipo);

				//Verifica se teve atribuição
				if (yyvsp[-1].tipo.compare("null"))
				{
					if (yyvsp[-3].tipo.compare(yyvsp[-1].tipo))
						yyval.traducao = yyvsp[-1].traducao + "\t" + nomeTemp + " = (" + yyvsp[-3].tipo + ") " + yyvsp[-1].label + ";\n";
					else
						yyval.traducao = yyvsp[-1].traducao + "\t" + nomeTemp + " = " + yyvsp[-1].label + ";\n";
				}
			;
    break;}
case 28:
#line 672 "sintatica.y"
{
				//Transfere para tradução de comando a tradução de DECLARACAO
				yyval.traducao =  yyvsp[0].traducao;
			;
    break;}
case 29:
#line 677 "sintatica.y"
{
				//Transfere para tradução de comando a tradução de ATRIBUICAO
				yyval.traducao =  yyvsp[0].traducao;
			;
    break;}
case 30:
#line 682 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 31:
#line 686 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 32:
#line 690 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 33:
#line 694 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 34:
#line 698 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 35:
#line 702 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 36:
#line 706 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 37:
#line 710 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 38:
#line 716 "sintatica.y"
{
				//Busca na tabela
				variavel var;

				//Tenta buscar a variável
				buscaVariavel(yyvsp[-2].label, var);

				yyval.traducao = "\tcin >> " + var.identificacao + ";\n";
			;
    break;}
case 39:
#line 728 "sintatica.y"
{
				yyval.traducao = yyvsp[-2].traducao 
				+ "\tcout >> " + yyvsp[-2].label + ";\n";	
			;
    break;}
case 40:
#line 734 "sintatica.y"
{
				//Cria e insere variáveis
				string nomeTemp1 = genTemp();
				insereVariavel(genNomeGen(), "char*" , nomeTemp1);

				string nomeTemp2 = nomeTemp1 + "_s";
				insereVariavel(genNomeGen(), "int" , nomeTemp2);

				int size = yyvsp[0].label.length() - 1;

				yyval.traducao = "\t" + nomeTemp2 + " = " + to_string(size) + ";\n"
				+ "\t" + nomeTemp1 + " = (char*) malloc (sizeof(char) * " + nomeTemp2 + ");\n"
				+ "\t" + "strcpy(" + nomeTemp1 + ", " + yyvsp[0].label + ");\n";

				yyval.tipo = "char*";

				yyval.label = nomeTemp1;


				//$$.traducao =  $1.label;
			;
    break;}
case 41:
#line 756 "sintatica.y"
{
				//Busca na tabela
				variavel var;

				//Tenta buscar a variável
				buscaVariavel(yyvsp[0].label, var);

				yyval.label = var.identificacao;
			;
    break;}
case 42:
#line 768 "sintatica.y"
{
				yyval.tipo = "int";

			;
    break;}
case 43:
#line 773 "sintatica.y"
{
				yyval.tipo = "real";
			;
    break;}
case 44:
#line 777 "sintatica.y"
{
				yyval.tipo = "BOOL";
			;
    break;}
case 45:
#line 781 "sintatica.y"
{
				yyval.tipo = "char";
			;
    break;}
case 46:
#line 785 "sintatica.y"
{
				yyval.tipo = "char*";

			;
    break;}
case 47:
#line 793 "sintatica.y"
{

				//Criação de variável temporária
				string nometemp = genTemp();

				//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
				//Adiciona na tabela
				insereVariavel(genNomeGen(), "BOOL", nometemp);

				//Guarda o tipo da Expressão resultante em E
				yyval.tipo = "BOOL";


				//Verifica a conversão int para bool
				if (!yyvsp[-2].tipo.compare("BOOL") && !yyvsp[0].tipo.compare("int"))
				{

					//Verifica se veio apenas um número
					if (!(yyvsp[0].label.find("temp") != std::string::npos)) 
					{
    					//Criação de variável temporária
						string nometemp1_b = genTemp();
						//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
						//Adiciona na tabela
						insereVariavel(genNomeGen(), "int", nometemp1_b);

						yyvsp[0].traducao = yyvsp[0].traducao +
						"\t" + nometemp1_b + " = " + yyvsp[0].label + ";\n";

						yyvsp[0].label = nometemp1_b;
					}


					//Criação de variável temporária
					string nometemp1 = genTemp();
					//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
					//Adiciona na tabela
					insereVariavel(genNomeGen(), "BOOL", nometemp1);

					//Transforma de inteiro para bool
					yyvsp[0].traducao = yyvsp[0].traducao 
					+ "\t" + nometemp1 + " = " + yyvsp[0].label + " != 0;\n"
					+ "\tif(" + nometemp1 + ")" 
					+ "\n\t" + yyvsp[0].label + " = TRUE;\n";

				}
				else if (!yyvsp[0].tipo.compare("BOOL") && !yyvsp[-2].tipo.compare("int"))
				{
					//Verifica se veio apenas um número
					if (!(yyvsp[-2].label.find("temp") != std::string::npos)) 
					{
    					//Criação de variável temporária
						string nometemp1_b = genTemp();
						//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
						//Adiciona na tabela
						insereVariavel(genNomeGen(), "int", nometemp1_b);

						yyvsp[-2].traducao = yyvsp[-2].traducao +
						"\t" + nometemp1_b + " = " + yyvsp[-2].label + ";\n";

						yyvsp[-2].label = nometemp1_b;
					}


					//Criação de variável temporária
					string nometemp1 = genTemp();
					//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
					//Adiciona na tabela
					insereVariavel(genNomeGen(), "BOOL", nometemp1);

					//Transforma de inteiro para bool
					yyvsp[-2].traducao = yyvsp[-2].traducao 
					+ "\t" + nometemp1 + " = " + yyvsp[-2].label + " != 0;\n"
					+ "\tif(" + nometemp1 + ")" 
					+ "\n\t" + yyvsp[-2].label + " = TRUE;\n";
				}

				//Passa para EL a tradução
				yyval.traducao = yyvsp[-2].traducao + yyvsp[0].traducao
				+ "\t" + nometemp + " = " + yyvsp[-2].label + yyvsp[-1].traducao + yyvsp[0].label + ";\n";

				//Passa para E seu valor de temporária
				yyval.label = nometemp;
			;
    break;}
case 48:
#line 878 "sintatica.y"
{

				//Criação de variável temporária
				string nometemp = genTemp();

				//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
				//Adiciona na tabela
				insereVariavel(genNomeGen(), "BOOL", nometemp);

				//Guarda o tipo da Expressão resultante em E
				yyval.tipo = "BOOL";
				//Passa para E seu valor de temporária
				yyval.label = nometemp;

				yyval.traducao = "\t" + nometemp + " = " + yyvsp[0].label + " != 0;\n";
			;
    break;}
case 49:
#line 897 "sintatica.y"
{
				//Criação de variável temporária
				//string nometemp = genTemp();

				//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
				//Adiciona na tabela
				//insereVariavel(genNomeGen(), "BOOL", nometemp);



				yyval.traducao = yyvsp[0].traducao ;
				//+ "\t" + nometemp + " = " + $1.label + " != 0;\n"
				//+ "\tif(" + nometemp + ")" 
				//+ "\n\t\t" + $1.label + " = TRUE;\n";
				yyval.tipo = yyvsp[0].tipo;
				yyval.label = yyvsp[0].label;
			;
    break;}
case 50:
#line 915 "sintatica.y"
{
				yyval.tipo = "char";
				yyval.label = yyvsp[0].label;
			;
    break;}
case 51:
#line 920 "sintatica.y"
{

			if (yyvsp[0].label.compare("true"))
				yyval.label = "FALSE";
			else
				yyval.label = "TRUE";

				yyval.tipo = "BOOL";
			;
    break;}
case 52:
#line 930 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
				yyval.tipo = yyvsp[0].tipo;
				yyval.label = yyvsp[0].label;
			;
    break;}
case 53:
#line 938 "sintatica.y"
{
				yyval.traducao = " == ";
			;
    break;}
case 54:
#line 942 "sintatica.y"
{
				yyval.traducao = " != ";
			;
    break;}
case 55:
#line 946 "sintatica.y"
{
				yyval.traducao = " <= ";
			;
    break;}
case 56:
#line 950 "sintatica.y"
{
				yyval.traducao = " >= ";
			;
    break;}
case 57:
#line 954 "sintatica.y"
{
				yyval.traducao = " > ";
			;
    break;}
case 58:
#line 958 "sintatica.y"
{
				yyval.traducao = " < ";
			;
    break;}
case 59:
#line 964 "sintatica.y"
{
				//Verifica se a expressão é válida
				atualizaRegraExprAritimetica(yyvsp[-2], yyvsp[0]);

				//Criação de variável temporária
				string nometemp = genTemp();

				//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
				//Adiciona na tabela
				insereVariavel(genNomeGen(), yyvsp[-2].tipo, nometemp);

				//Guarda o tipo da Expressão resultante em E
				yyval.tipo = yyvsp[-2].tipo;

				//Passa para E a tradução
				yyval.traducao = yyvsp[-2].traducao + yyvsp[0].traducao 
				//+ "\t" + $1.tipo + " " + nometemp + ";\n"
				+ "\t" + nometemp + " = " + yyvsp[-2].label + " / " + yyvsp[0].label + ";\n";

				//Passa para E seu valor de temporária
				yyval.label = nometemp;
			;
    break;}
case 60:
#line 987 "sintatica.y"
{
				//Verifica se a expressão é válida
				atualizaRegraExprAritimetica(yyvsp[-2], yyvsp[0]);

				//Criação de variável temporária
				string nometemp = genTemp();

				//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
				//Adiciona na tabela
				insereVariavel(genNomeGen(), yyvsp[-2].tipo, nometemp);

				//Guarda o tipo da Expressão resultante em E
				yyval.tipo = yyvsp[-2].tipo;

				//Passa para E a tradução
				yyval.traducao = yyvsp[-2].traducao + yyvsp[0].traducao 
				//+ "\t" + $1.tipo + " " + nometemp + ";\n"
				+ "\t" + nometemp + " = " + yyvsp[-2].label + " * " + yyvsp[0].label + ";\n";

				//Passa para E seu valor de temporária
				yyval.label = nometemp;

			;
    break;}
case 61:
#line 1011 "sintatica.y"
{

				//Verifica se a expressão é válida
				atualizaRegraExprAritimetica(yyvsp[-2], yyvsp[0]);

				//Criação de variável temporária
				string nometemp = genTemp();

				//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
				//Adiciona na tabela
				insereVariavel(genNomeGen(), yyvsp[-2].tipo, nometemp);

				//Guarda o tipo da Expressão resultante em E
				yyval.tipo = yyvsp[-2].tipo;

				//Passa para E a tradução
				yyval.traducao = yyvsp[-2].traducao + yyvsp[0].traducao 
				+ "\t" + nometemp + " = " + yyvsp[-2].label + " + " + yyvsp[0].label + ";\n";

				//Passa para E seu valor de temporária
				yyval.label = nometemp;

			;
    break;}
case 62:
#line 1035 "sintatica.y"
{
				//Verifica se a expressão é válida
				atualizaRegraExprAritimetica(yyvsp[-2], yyvsp[0]);

				//Criação de variável temporária
				string nometemp = genTemp();

				//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
				//Adiciona na tabela
				insereVariavel(genNomeGen(), yyvsp[-2].tipo, nometemp);

				//Guarda o tipo da Expressão resultante em E
				yyval.tipo = yyvsp[-2].tipo;

				//Passa para E a tradução
				yyval.traducao = yyvsp[-2].traducao + yyvsp[0].traducao 
				//+ "\t" + $1.tipo + " " + nometemp + ";\n"
				+ "\t"  + nometemp + " = " + yyvsp[-2].label + " - " + yyvsp[0].label + ";\n";

				//Passa para E seu valor de temporária
				yyval.label = nometemp;

			;
    break;}
case 63:
#line 1059 "sintatica.y"
{
				//Passa para E o tipo e seu valor
				yyval.tipo = "int";
				yyval.label = yyvsp[0].label;
			;
    break;}
case 64:
#line 1065 "sintatica.y"
{
				//Passa para E o tipo e seu valor
				yyval.tipo = "real";
				yyval.label = yyvsp[0].label;
			;
    break;}
case 65:
#line 1073 "sintatica.y"
{

				//Busca na tabela
				variavel var;
				

				//Tenta buscar a variável
				buscaVariavel(yyvsp[0].label, var);

				//Passa o tipo e o nome para E
				yyval.tipo = var.tipo;
				yyval.label = var.identificacao; 
			;
    break;}
case 66:
#line 1087 "sintatica.y"
{
				//Busca na tabela
				variavel var;
				
				//Tenta buscar a variável
				buscaVariavel(yyvsp[0].label, var);

				//Criação de variável temporária
				string nometemp = genTemp();

				//Ja foram convertidas se era possível, basta pegar o tipo de qualquer  um
				//Adiciona na tabela
				insereVariavel(genNomeGen(), yyvsp[-2].tipo, nometemp);

				yyval.traducao = "\t" + nometemp + " = (" + yyvsp[-2].tipo + ") " + var.identificacao + "\n";

				//Passa o tipo e o nome para E
				yyval.tipo = yyvsp[-2].tipo;
				yyval.label = nometemp; 
			;
    break;}
case 67:
#line 1109 "sintatica.y"
{
				//Passa seu nome literal para ID

				yyval.label = yyvsp[0].label;
			;
    break;}
case 68:
#line 1116 "sintatica.y"
{
				
				string nometemp = genTemp();
				insereVariavel(genNomeGen(), "BOOL", nometemp);
				string label = labelStackEnd.top();
				labelStackEnd.pop();

				yyval.traducao = yyvsp[-3].traducao + "\t" + nometemp + " = !" + 
				yyvsp[-3].label + ";\n" + "\tif" + "(" + nometemp + ")" + "\n\tgoto " + label + ";\n" + 
				yyvsp[-1].traducao + "\tgoto " + yyvsp[0].tipo + ";\n" + yyvsp[0].traducao +"\t"+ yyvsp[0].tipo + ":\n";
			;
    break;}
case 69:
#line 1128 "sintatica.y"
{	
				variavel var;
				_switch swt = switchVar.top();
				switchVar.pop();
				laco swAtual = pilhaLaco.back();
								
				buscaVariavel(yyvsp[-5].label, var);

				if(var.tipo.compare(swt.tipo))
				{
					cout << "switch and case have different types\n";
					exit(1);
				}

				yyval.traducao = "\t" + swAtual.labelinicio + ":\n\t" + swt.comp + " = " + 
				var.identificacao + ";\n" + yyvsp[-1].traducao + "\t" + swAtual.labelfim + ":\n";

				 //Desempilha switch
				pilhaLaco.pop_back();
			;
    break;}
case 70:
#line 1150 "sintatica.y"
{
				//Passa para E o tipo e seu valor
				yyval.tipo = "int";
				yyval.label = yyvsp[0].label;
			;
    break;}
case 71:
#line 1156 "sintatica.y"
{
				yyval.tipo = "char";
				yyval.label = yyvsp[0].label;
			;
    break;}
case 72:
#line 1161 "sintatica.y"
{
				yyval.tipo = "string";
				yyval.label = yyvsp[0].label;
			;
    break;}
case 73:
#line 1167 "sintatica.y"
{
				yyval.traducao = yyvsp[-1].traducao + yyvsp[0].traducao;
			;
    break;}
case 74:
#line 1171 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 75:
#line 1175 "sintatica.y"
{
				yyval.traducao = "";
			;
    break;}
case 76:
#line 1181 "sintatica.y"
{
				_switch swt;
				string labelAt = gerarLabel(0);
				if(switchVar.empty())
				{
					swt.var = genTemp();
					swt.comp = genTemp();
					swt.res = genTemp();
					swt.tipo = yyvsp[-2].tipo;
					switchVar.push(swt);
					insereVariavel(genNomeGen(), yyvsp[-2].tipo, swt.var);
					insereVariavel(genNomeGen(), yyvsp[-2].tipo, swt.res);
					insereVariavel(genNomeGen(), yyvsp[-2].tipo, swt.comp);
					
				}

				swt = switchVar.top();
				
				if(swt.tipo.compare(yyvsp[-2].tipo))
				{
					cout << "Error in type switch case " + yyvsp[-2].tipo + " not equal " + swt.tipo + "\n";
					exit(1);
				}
				
				yyval.traducao = "\t" + swt.var + " = " + yyvsp[-2].label + ";\n\t" + 
				swt.res + " = " + "!(" + swt.comp + " == " + swt.var + ");" + "\n\t"
				"if(" + swt.res + ")" + "\n\t" + "goto " + labelAt + ";"+ "\n" + 
				yyvsp[0].traducao + "\t" + labelAt + ":" + "\n" ;
			;
    break;}
case 77:
#line 1212 "sintatica.y"
{
				yyval.traducao = yyvsp[0].traducao;
			;
    break;}
case 78:
#line 1217 "sintatica.y"
{
				
				string nometemp = genTemp();
				string labelInit = gerarLabel(0);
				string labelEnd = labelStackEnd.top();
				labelStackEnd.pop();		

				insereVariavel(genNomeGen(), "BOOL", nometemp);

				yyval.traducao = "\t" + labelInit + ":\n"+ yyvsp[-3].traducao + "\t" + nometemp + "= !" + 
				yyvsp[-3].label + ";\n\tif" + "(" + nometemp + ")" + "\n\tgoto " + labelEnd + ";\n" + 
				yyvsp[-1].traducao + "\tgoto " + yyvsp[0].tipo + ";\n" + yyvsp[0].traducao ;
				yyval.tipo = yyvsp[0].tipo;

				labelEnd = gerarLabel(-1);
				labelStackEnd.push(labelEnd);
			;
    break;}
case 79:
#line 1235 "sintatica.y"
{
				
				string label = gerarLabelEndif();
				string labelelse = gerarLabel(0);
				labelStackEnd.push(label);
				labelStackEnd.push(labelelse);
				yyval.tipo = label;
				yyval.traducao = "\t" + labelelse + ":\n" + yyvsp[0].traducao;

			;
    break;}
case 80:
#line 1246 "sintatica.y"
{
				string label = gerarLabelEndif();
				labelStackEnd.push(label);
				yyval.tipo = label;
			;
    break;}
case 81:
#line 1253 "sintatica.y"
{
				_function func;
				
				func = functions.top();

				func.label =  yyvsp[-8].label;

				yyval.traducao = yyvsp[-2].tipo + " " + yyvsp[-8].label  + 
				"(" + yyvsp[-6].traducao + yyvsp[-5].traducao + ")\n{\n" + yyvsp[0].traducao + "\n}\n";
			;
    break;}
case 83:
#line 1266 "sintatica.y"
{
				yyval.traducao = "\treturn " + yyvsp[-1].traducao + ";\n";
			;
    break;}
case 84:
#line 1271 "sintatica.y"
{
				yyval.traducao = yyvsp[0].label;
			;
    break;}
case 85:
#line 1275 "sintatica.y"
{

			;
    break;}
case 86:
#line 1279 "sintatica.y"
{

			;
    break;}
case 87:
#line 1284 "sintatica.y"
{
				yyval.traducao = yyvsp[-2].traducao + yyvsp[-1].traducao + yyvsp[0].traducao;
			;
    break;}
case 88:
#line 1288 "sintatica.y"
{
				yyval.traducao = "";
			;
    break;}
case 89:
#line 1293 "sintatica.y"
{
				yyval.traducao = ","
			;
    break;}
case 90:
#line 1298 "sintatica.y"
{
				_function func;

				variavel var;

				var.identificacao = genTemp();
				var.tipo = yyvsp[-1].tipo;
				var.nome = genNomeGen();

				func.functionContext.push_back(var);
				functions.push(func);
				//insereVariavel(var.nome, var.tipo, var.identificacao);

				yyval.traducao = yyvsp[-1].tipo + " " + var.identificacao;
			;
    break;}
case 91:
#line 1316 "sintatica.y"
{

			;
    break;}
case 92:
#line 1321 "sintatica.y"
{
				yyval.traducao = yyvsp[-1].traducao + yyvsp[0].traducao;
			;
    break;}
case 93:
#line 1325 "sintatica.y"
{
				yyval.traducao = "";
			;
    break;}
case 94:
#line 1330 "sintatica.y"
{
				yyval.traducao = yyvsp[0]. traducao;
			;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 1335 "sintatica.y"


#include "lex.yy.c"

int yyparse();

int main( int argc, char* argv[] )
{

	empilhaContexto();

	yyparse();

	return 0;
}

void yyerror( string MSG )
{
	cout << MSG << endl;
	exit (0);
}				
